apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app-deployment
  name: my-app-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: my-app-deployment
  type: NodePort
status:
  loadBalancer: {}
